# Generated by Django 5.1.4 on 2025-01-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_percent', models.FloatField()),
                ('ram_used_gb', models.FloatField()),
                ('disk_used_gb', models.FloatField()),
                ('uptime_hours', models.FloatField()),
                ('temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
